### ISSUE TITLE
"Undefined constant "VERSION"" at be_syncCtoPro_popup_overview.html5 line 189

### ISSUE THREAD

**Issue by kasake07** [menatwork/syncCtoPro#1]
Hi,
Contao 5.3
PHP 8.2

This critical error occurs when syncing (Differentiated synchronization). Additionally before the error there is a long list of warning messages which makes the log file over 100MB.

Here are the last rows of my log file:
```
...
[2025-06-03T14:02:28.113463+02:00] php.WARNING: Warning: Undefined array key "pid" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"pid\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Controller\\Diff.php:794)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.113999+02:00] php.WARNING: Warning: Undefined array key "pid" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"pid\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Controller\\Diff.php:794)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.114477+02:00] php.WARNING: Warning: Undefined array key "pid" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"pid\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Controller\\Diff.php:794)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.115013+02:00] php.WARNING: Warning: Undefined array key "pid" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"pid\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Controller\\Diff.php:794)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.115604+02:00] php.WARNING: Warning: Undefined array key "pid" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"pid\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Controller\\Diff.php:794)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.116019+02:00] php.WARNING: Warning: Undefined array key "pid" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"pid\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Controller\\Diff.php:794)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.116571+02:00] php.WARNING: Warning: Undefined array key "pid" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"pid\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Controller\\Diff.php:794)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.117583+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Controller\\Diff.php:861)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.119255+02:00] php.WARNING: Warning: Attempt to read property "base" on null {"exception":"[object] (ErrorException(code: 0): Warning: Attempt to read property \"base\" on null at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:44)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.119331+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:51)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.119487+02:00] php.WARNING: Warning: Undefined array key "blocked" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"blocked\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:59)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.119540+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:110)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.119750+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.119811+02:00] php.WARNING: Warning: Undefined array key "blocked" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"blocked\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:59)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.119910+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.119966+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120015+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120064+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120112+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120160+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120223+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120273+02:00] php.WARNING: Warning: Undefined array key "blocked" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"blocked\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:59)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120320+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:110)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120433+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120486+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120541+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120626+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120680+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120729+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120778+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:139)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120844+02:00] php.WARNING: Warning: Attempt to read property "base" on null {"exception":"[object] (ErrorException(code: 0): Warning: Attempt to read property \"base\" on null at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:171)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.120887+02:00] php.WARNING: Warning: Undefined array key "show_differences" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"show_differences\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:178)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:28.123100+02:00] request.CRITICAL: Uncaught PHP Exception Error: "Undefined constant "VERSION"" at be_syncCtoPro_popup_overview.html5 line 189 {"exception":"[object] (Error(code: 0): Undefined constant \"VERSION\" at D:\\vhost\\php8.2\\contao-lte\\vendor\\menatwork\\syncctopro\\src\\Resources\\contao\\templates\\be_syncCtoPro_popup_overview.html5:189)"} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}
[2025-06-03T14:02:38.942856+02:00] messenger.INFO: Stopping worker. {"transport_names":["contao_prio_high"]} {"request_uri":"http://contao-lte.local/syncCto/pro/databasePopup?direction=To&id=1&language=de&view=overview","request_method":"GET"}

```

**Comment by stefanheimes** [comment]
Should be fixed in 3.0.3

**Comment by kasake07** [comment]
Hi,

the sync still fails, leaving a big log file with similar warnings. 
The last 100 lines of the log file:

```
[2025-08-13T09:14:08.261456+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.261525+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.261572+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.261649+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.261693+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.261731+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.261813+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.261852+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.261923+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262032+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262117+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262204+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262311+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262354+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262399+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262491+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262533+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262588+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262667+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262715+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262759+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262840+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262880+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.262958+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263008+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263047+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263125+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263196+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263237+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263329+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263383+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263421+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263491+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263553+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263594+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263657+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263734+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263775+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263855+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.263960+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264013+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264078+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264151+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264194+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264248+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264329+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264383+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264422+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264475+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264537+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264576+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264632+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264692+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264731+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264786+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264857+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264896+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.264956+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265028+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265079+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265148+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265211+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265250+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265350+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265416+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265454+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265502+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265591+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265655+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265768+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265824+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265864+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265937+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.265998+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266058+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266172+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266224+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266276+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266345+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266399+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266442+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266514+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266559+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266597+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266670+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266720+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266758+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266833+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266878+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.266946+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.267026+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.267079+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.267168+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.267228+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.267290+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.267400+02:00] php.WARNING: Warning: Undefined array key "protected" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"protected\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1879)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.267486+02:00] php.WARNING: Warning: Undefined array key "published" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"published\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1866)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.267526+02:00] php.WARNING: Warning: Undefined array key "hide" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"hide\" at /code/vendor/menatwork/syncctopro/src/Controller/Diff.php:1871)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:08.292452+02:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\OutOfMemoryError: "Error: Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes)" at ErrorHandler.php line 732 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) at /code/vendor/symfony/error-handler/ErrorHandler.php:732)"} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
[2025-08-13T09:14:16.195512+02:00] messenger.INFO: Stopping worker. {"transport_names":["contao_prio_high"]} {"request_uri":"https://example.com/syncCto/pro/databasePopup?direction=To&id=2&language=de&view=overview","request_method":"GET"}
```

Thank you
